name: Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: |
        sudo apt-get update      
        sudo apt-get install curl build-essential make cmake libc6-dev      
        sudo apt-get -qy install gcc g++ gfortran
        sudo apt-get -qy install python3 python3-pip python3-pytest
        sudo apt-get -qy install python3-numpy python3-scipy python3-matplotlib
        sudo apt-get install python3-opencv
        pip install pybind11
        cd /usr/bin ; sudo ln -sf py.test-3 py.test
          
  
    - name: make
      run: |
        cd proj
        make